-- The base schema: the tables, functions, trigger and policies that predate
-- the numbered migrations and exist only in the live database. Captured from
-- production on 5 September 2026 so a fresh project can be rebuilt: run this
-- first, then migrations/0001 onward. Reference only — already applied.
--
-- Later migrations have since added to some of these objects (for example
-- purchases.refunded_at from 0047 and the ledger recency index from 0048);
-- those lines are kept here so the snapshot matches the live shape today.

begin;

-- ---------------------------------------------------------------------------
-- Accounts and credits
-- ---------------------------------------------------------------------------

create table if not exists public.profiles (
	id uuid primary key references auth.users (id) on delete cascade,
	email text not null,
	created_at timestamptz not null default now(),
	is_admin boolean not null default false,
	is_restricted boolean not null default false,
	is_staff boolean not null default false,
	display_name text not null default ''
);

create table if not exists public.credit_packs (
	id text primary key,
	name text not null,
	credits integer not null check (credits > 0),
	price_pence integer not null check (price_pence > 0)
);

insert into public.credit_packs (id, name, credits, price_pence) values
	('starter', 'Starter', 500, 299),
	('growth', 'Growth', 1200, 599),
	('scale', 'Scale', 3000, 1299)
on conflict (id) do nothing;

create table if not exists public.credit_ledger (
	id bigint generated by default as identity primary key,
	user_id uuid not null references auth.users (id) on delete cascade,
	delta integer not null,
	reason text not null,
	created_at timestamptz not null default now()
);

create index if not exists credit_ledger_by_user_recency
	on public.credit_ledger (user_id, created_at desc);

create table if not exists public.purchases (
	id uuid primary key default gen_random_uuid(),
	user_id uuid not null references auth.users (id) on delete cascade,
	pack_id text not null references public.credit_packs (id),
	credits integer not null,
	amount_pence integer not null,
	currency text not null default 'gbp',
	stripe_checkout_session_id text,
	status text not null default 'placeholder_paid',
	created_at timestamptz not null default now(),
	refunded_at timestamptz
);

-- ---------------------------------------------------------------------------
-- The original agent conversation and Workflow Map storage
-- ---------------------------------------------------------------------------

create table if not exists public.agent_sessions (
	id uuid primary key,
	user_id uuid not null references auth.users (id) on delete cascade,
	created_at timestamptz not null default now()
);

create table if not exists public.agent_messages (
	id bigint generated by default as identity primary key,
	session_id uuid not null references public.agent_sessions (id) on delete cascade,
	user_id uuid not null references auth.users (id) on delete cascade,
	author text not null check (author in ('user', 'agent')),
	body text not null,
	created_at timestamptz not null default now(),
	workflow_id uuid not null references public.workflows (id) on delete cascade
);

create index if not exists agent_messages_by_workflow
	on public.agent_messages (workflow_id, created_at);

create table if not exists public.workflow_maps (
	id bigint generated by default as identity primary key,
	user_id uuid not null references auth.users (id) on delete cascade,
	version integer not null,
	model jsonb not null,
	created_at timestamptz not null default now(),
	workflow_id uuid not null references public.workflows (id) on delete cascade,
	unique (workflow_id, version)
);

create table if not exists public.map_viewers (
	id bigint generated by default as identity primary key,
	owner_id uuid not null references auth.users (id) on delete cascade,
	viewer_email text not null,
	created_at timestamptz not null default now(),
	workflow_id uuid not null references public.workflows (id) on delete cascade,
	unique (workflow_id, viewer_email)
);

-- ---------------------------------------------------------------------------
-- Expertise brain sources and events
-- ---------------------------------------------------------------------------

create table if not exists public.brain_sources (
	id uuid primary key default gen_random_uuid(),
	user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
	filename text not null,
	mime_type text not null,
	byte_count integer not null,
	storage_path text not null,
	status text not null default 'uploaded'
		check (status in ('uploaded', 'ingested', 'failed', 'proposed', 'rejected')),
	summary text not null default '',
	created_at timestamptz not null default now(),
	brain_id uuid not null references public.domain_brains (id) on delete cascade
);

create table if not exists public.brain_events (
	id bigint generated by default as identity primary key,
	user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
	kind text not null check (kind in (
		'source_ingested', 'source_removed', 'context_created', 'context_updated',
		'context_deleted', 'page_created', 'page_updated', 'page_deleted',
		'question_answered', 'brain_exported', 'changes_proposed', 'changes_approved',
		'changes_rejected', 'edition_published', 'model_pruned'
	)),
	detail jsonb not null default '{}'::jsonb,
	source_id uuid references public.brain_sources (id) on delete set null,
	page_slug text,
	created_at timestamptz not null default now(),
	brain_id uuid not null references public.domain_brains (id) on delete cascade
);

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.credit_packs enable row level security;
alter table public.credit_ledger enable row level security;
alter table public.purchases enable row level security;
alter table public.agent_sessions enable row level security;
alter table public.agent_messages enable row level security;
alter table public.workflow_maps enable row level security;
alter table public.map_viewers enable row level security;
alter table public.brain_sources enable row level security;
alter table public.brain_events enable row level security;

create policy "read own profile" on public.profiles for select using (auth.uid() = id);
create policy "read credit packs" on public.credit_packs for select using (true);
create policy "read own ledger" on public.credit_ledger for select using (auth.uid() = user_id);
create policy "read own purchases" on public.purchases for select using (auth.uid() = user_id);
create policy "read own sessions" on public.agent_sessions for select using (auth.uid() = user_id);
create policy "read own messages" on public.agent_messages for select using (auth.uid() = user_id);
create policy "write own messages" on public.agent_messages for insert with check (
	auth.uid() = user_id
	and exists (select 1 from public.agent_sessions
		where agent_sessions.id = agent_messages.session_id and agent_sessions.user_id = auth.uid())
);
create policy "read own maps" on public.workflow_maps for select using (auth.uid() = user_id);
create policy "write own maps" on public.workflow_maps for insert with check (auth.uid() = user_id);
create policy "manage own viewers" on public.map_viewers for all
	using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
create policy "Owners read their sources" on public.brain_sources for select using (user_id = auth.uid());
create policy "Owners add sources" on public.brain_sources for insert with check (user_id = auth.uid());
create policy "Owners update their sources" on public.brain_sources for update using (user_id = auth.uid());
create policy "Owners remove their sources" on public.brain_sources for delete using (user_id = auth.uid());
create policy "Brain owners read all sources" on public.brain_sources for select using (public.is_brain_owner(brain_id));
create policy "Brain owners update all sources" on public.brain_sources for update using (public.is_brain_owner(brain_id));
create policy "Brain owners remove all sources" on public.brain_sources for delete using (public.is_brain_owner(brain_id));
create policy "Collaborators read shared sources" on public.brain_sources for select using (public.is_brain_collaborator(brain_id));
create policy "Owners read their events" on public.brain_events for select using (user_id = auth.uid());
create policy "Owners add events" on public.brain_events for insert with check (user_id = auth.uid());
create policy "Brain owners read all brain events" on public.brain_events for select using (public.is_brain_owner(brain_id));
create policy "Collaborators read shared events" on public.brain_events for select using (public.is_brain_collaborator(brain_id));

-- ---------------------------------------------------------------------------
-- Admin gates
-- ---------------------------------------------------------------------------

create or replace function public.require_admin()
returns void
language plpgsql
security definer
set search_path to 'public'
as $$
begin
	if not coalesce((select is_admin from profiles where id = auth.uid()), false) then
		raise exception 'not_admin';
	end if;
end;
$$;

create or replace function public.assert_admin()
returns void
language plpgsql
security definer
set search_path to 'public'
as $$
begin
	if not exists (select 1 from public.profiles where id = auth.uid() and is_admin) then
		raise exception 'admin_only';
	end if;
end;
$$;

create or replace function public.is_project_manager()
returns boolean
language sql
stable
security definer
set search_path to 'public'
as $$
	select exists (
		select 1 from public.profiles
		where id = auth.uid() and (is_staff or is_admin) and not is_restricted
	);
$$;

-- ---------------------------------------------------------------------------
-- Signup: every account gets a profile; the founder's address is the admin.
-- ---------------------------------------------------------------------------

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $$
begin
	insert into profiles (id, email, is_admin)
	values (new.id, coalesce(new.email, ''), coalesce(new.email, '') = 'jamesbeadle1989@gmail.com');
	return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
	after insert on auth.users
	for each row execute function public.handle_new_user();

create or replace function public.set_display_name(new_display_name text)
returns void
language sql
security definer
set search_path to 'public'
as $$
	update public.profiles set display_name = trim(new_display_name) where id = auth.uid();
$$;

-- ---------------------------------------------------------------------------
-- Credits
-- ---------------------------------------------------------------------------

create or replace function public.credit_balance()
returns integer
language sql
security definer
set search_path to 'public'
as $$
	select coalesce(sum(delta), 0)::integer from credit_ledger where user_id = auth.uid();
$$;

create or replace function public.complete_stripe_purchase(
	user_identifier uuid,
	pack_identifier text,
	checkout_session_identifier text
)
returns void
language plpgsql
security definer
set search_path to 'public'
as $$
declare
	pack credit_packs%rowtype;
begin
	perform pg_advisory_xact_lock(hashtext(checkout_session_identifier));
	if exists (select 1 from purchases where stripe_checkout_session_id = checkout_session_identifier) then
		return;
	end if;
	select * into pack from credit_packs where id = pack_identifier;
	if not found then
		raise exception 'unknown_pack';
	end if;
	insert into purchases (user_id, pack_id, credits, amount_pence, stripe_checkout_session_id, status)
	values (user_identifier, pack.id, pack.credits, pack.price_pence, checkout_session_identifier, 'paid');
	insert into credit_ledger (user_id, delta, reason)
	values (user_identifier, pack.credits, 'purchase:' || pack.id);
end;
$$;

revoke execute on function public.complete_stripe_purchase(uuid, text, text) from public, anon, authenticated;
grant execute on function public.complete_stripe_purchase(uuid, text, text) to service_role;

create or replace function public.admin_grant_credits(target_email text, credit_amount integer, note text)
returns integer
language plpgsql
security definer
set search_path to 'public'
as $$
declare
	target_user_id uuid;
begin
	perform require_admin();
	if credit_amount <= 0 or credit_amount > 100000 then
		raise exception 'invalid_amount';
	end if;
	select id into target_user_id from profiles where email = target_email;
	if not found then
		raise exception 'unknown_user';
	end if;
	insert into credit_ledger (user_id, delta, reason)
	values (target_user_id, credit_amount, 'admin_grant:' || note);
	return (select sum(delta) from credit_ledger where user_id = target_user_id)::integer;
end;
$$;

create or replace function public.spend_for_agent_reply(session_identifier uuid)
returns integer
language plpgsql
security definer
set search_path to 'public'
as $$
declare
	credits_per_reply constant integer := 10;
begin
	if auth.uid() is null then
		raise exception 'not_signed_in';
	end if;
	if (select is_restricted from profiles where id = auth.uid()) then
		raise exception 'account_restricted';
	end if;
	perform pg_advisory_xact_lock(hashtext(auth.uid()::text));
	insert into agent_sessions (id, user_id) values (session_identifier, auth.uid())
	on conflict (id) do nothing;
	if credit_balance() < credits_per_reply then
		raise exception 'insufficient_credits';
	end if;
	insert into credit_ledger (user_id, delta, reason) values (auth.uid(), -credits_per_reply, 'agent_reply');
	return credit_balance();
end;
$$;

create or replace function public.spend_for_brain_question()
returns integer
language plpgsql
security definer
set search_path to 'public'
as $$
declare
	credits_per_question constant integer := 10;
begin
	if auth.uid() is null then
		raise exception 'not_signed_in';
	end if;
	if (select is_restricted from profiles where id = auth.uid()) then
		raise exception 'account_restricted';
	end if;
	perform pg_advisory_xact_lock(hashtext(auth.uid()::text));
	if credit_balance() < credits_per_question then
		raise exception 'insufficient_credits';
	end if;
	insert into credit_ledger (user_id, delta, reason) values (auth.uid(), -credits_per_question, 'brain_question');
	return credit_balance();
end;
$$;

create or replace function public.spend_for_brain_ingest(source_identifier uuid)
returns integer
language plpgsql
security definer
set search_path to 'public'
as $$
declare
	credits_per_ingest constant integer := 50;
begin
	if auth.uid() is null then
		raise exception 'not_signed_in';
	end if;
	if (select is_restricted from profiles where id = auth.uid()) then
		raise exception 'account_restricted';
	end if;
	perform pg_advisory_xact_lock(hashtext(auth.uid()::text));
	if not exists (select 1 from brain_sources where id = source_identifier and user_id = auth.uid()) then
		raise exception 'unknown_source';
	end if;
	if credit_balance() < credits_per_ingest then
		raise exception 'insufficient_credits';
	end if;
	insert into credit_ledger (user_id, delta, reason) values (auth.uid(), -credits_per_ingest, 'brain_ingest');
	return credit_balance();
end;
$$;

-- ---------------------------------------------------------------------------
-- Admin listings and switches
-- ---------------------------------------------------------------------------

create or replace function public.admin_list_users()
returns table(email text, credits integer, is_admin boolean, is_restricted boolean, joined_at timestamptz)
language plpgsql
security definer
set search_path to 'public'
as $$
begin
	perform require_admin();
	return query
	select p.email,
		coalesce((select sum(delta) from credit_ledger l where l.user_id = p.id), 0)::integer,
		p.is_admin, p.is_restricted, p.created_at
	from profiles p
	order by p.created_at desc;
end;
$$;

create or replace function public.admin_list_staff_flags()
returns table(email text, is_staff boolean)
language plpgsql
security definer
set search_path to 'public'
as $$
begin
	perform public.assert_admin();
	return query select profiles.email, profiles.is_staff from public.profiles;
end;
$$;

create or replace function public.admin_set_restriction(target_email text, restricted boolean)
returns void
language plpgsql
security definer
set search_path to 'public'
as $$
begin
	perform require_admin();
	update profiles set is_restricted = restricted where email = target_email;
	if not found then
		raise exception 'unknown_user';
	end if;
end;
$$;

create or replace function public.admin_set_staff(target_email text, staff boolean)
returns void
language plpgsql
security definer
set search_path to 'public'
as $$
begin
	perform public.assert_admin();
	update public.profiles set is_staff = staff where email = target_email;
end;
$$;

-- ---------------------------------------------------------------------------
-- Task comment notifications (the notifications table comes from
-- docs/sql/project-management-upgrade.sql)
-- ---------------------------------------------------------------------------

create or replace function public.notify_task_assignees_of_comment()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $$
begin
	insert into public.notifications (recipient_id, task_id, comment_id)
	select task_assignees.profile_id, new.task_id, new.id
	from public.task_assignees
	where task_assignees.task_id = new.task_id and task_assignees.profile_id <> new.author_id;
	return new;
end;
$$;

drop trigger if exists task_comment_notifications on public.task_comments;
create trigger task_comment_notifications
	after insert on public.task_comments
	for each row execute function public.notify_task_assignees_of_comment();

commit;
