import type { LegalSection } from '$lib/data/legalDocument';

export const termsEngagementSections: LegalSection[] = [
	{
		heading: 'The client portal',
		paragraphs: [
			'If we work for your business, we open the portal to the people you name. There they can see the projects we run for you, the goals and tasks inside them, and every request they have raised. A request is raised in plain English, discussed on its own thread, and becomes work only when we accept it. What that acceptance commits us to is set by your written agreement.',
			'You can attach files to a request when they are part of the ask. Attach only what the work needs, and nothing you are not entitled to share with us.'
		]
	},
	{
		heading: 'What we build for you',
		paragraphs: [
			'When we build something for your business, it is built for you and it is yours. Once the fees for that work are paid, you own what we deliver and the written record of how your business works that we produce alongside it. We keep the right to reuse the general know-how, techniques and non-specific components behind it, which is what lets us begin the next engagement from something rather than nothing.',
			'You are not locked in. You can take a copy of what we hold for you and end the engagement on the notice your agreement sets out. Where we host something for you, we will keep it running through a reasonable handover period and give you what you need to move it elsewhere, on terms agreed at the time.'
		]
	},
	{
		heading: 'Confidentiality',
		paragraphs: [
			'What we learn about your business during an engagement is confidential. We do not disclose it outside the people working on it, and we will not name you as a client, publish a case study, or describe the work publicly without your agreement in writing. The same obligation runs the other way for what we show you about how we work.'
		]
	},
	{
		heading: 'Connecting your own tools',
		paragraphs: [
			'You can connect Claude, or another tool that speaks the same protocol, to your portal — either with a token you mint in your account or by authorising an application. That connection can do what you can do, so a token is a secret: keep it safe, mint one per tool, and revoke anything you no longer use.',
			'You are responsible for what a connected tool does with your access, and for reading what an application asks for before you authorise it. We may revoke a token or an authorisation that is being misused.'
		]
	},
	{
		heading: 'AI-generated output',
		paragraphs: [
			'Parts of the portal are generated by AI: summaries, drafts, and replies to what you ask it. AI output can be incomplete, out of date or simply wrong, and none of it is legal, financial, tax or other professional advice. Check anything important before you act on it. Advice you can rely on comes from us in writing, under your agreement.'
		]
	}
];
