import type { LegalDocument } from './legalDocument';

export const termsOfService: LegalDocument = {
	title: 'Terms of service',
	metaDescription: 'The terms that govern your use of Your Business Today — accounts, credits, your content, and the services that run on your knowledge.',
	lastUpdatedOn: '21 August 2026',
	sections: [
		{
			heading: 'Who we are',
			paragraphs: [
				'Your Business Today is operated by Your Business Today Ltd, a company registered in England and Wales (“we”, “us”). You can reach us at consulting@yourbusiness.today.',
				'These terms govern your use of yourbusiness.today and every part of the service, including process maps, expertise brains, the Market, and the Hive Mind. By creating an account you agree to them. If you are using the service on behalf of a business, you confirm you have authority to bind that business.'
			]
		},
		{
			heading: 'Early access',
			paragraphs: [
				'The service is in early access. Tools may change, gain features, lose features, or be withdrawn as we build. Where a change materially affects something you have paid credits for, we will give you reasonable notice where we can.'
			]
		},
		{
			heading: 'Your account',
			paragraphs: [
				'You can sign in with Google, Microsoft, or an email address and password. Your account is yours alone: keep your credentials secure, and tell us promptly if you believe someone else has used them. You are responsible for activity that happens under your account, you must be at least 18, and the information you give us must be accurate and kept up to date.'
			]
		},
		{
			heading: 'Credits and payment',
			paragraphs: [
				'The tools are paid for with credits, bought in packs through our payment provider, Stripe. The price of each pack is shown before you buy, and the credit cost of each action — an agent reply, a document ingest, a question — is shown in the service before you take it.',
				'Credits are a prepayment for services, not money. They carry no cash value, earn no interest, and cannot be exchanged outside the service, although you can send credits to another account holder using the sending feature. Promotional credits we grant are free of charge and can be withdrawn if unused.',
				'If you change your mind about a pack within 14 days of buying it and have not spent any of its credits, contact us and we will refund it. Once credits from a pack have been spent, the work has been done and the pack is no longer refundable, except where the law says otherwise. Nothing in these terms limits your statutory rights as a consumer.'
			]
		},
		{
			heading: 'Your content',
			paragraphs: [
				'Everything you put into the service — documents you upload, answers you give the interviewer, and the maps and models built from them — remains yours. You grant us the licence we need to host, process, and display that content in order to run the service for you, and for nothing else.',
				'Your content is never sold, never pooled with other customers’ content, and never used to train models for anyone else. You can export your expertise brain as Markdown at any time, free of charge.',
				'You are responsible for having the right to upload what you upload, including any personal data it contains about other people.'
			]
		},
		{
			heading: 'AI-generated answers',
			paragraphs: [
				'The agents’ replies, maps, models, and answers are generated by AI. They can be incomplete, out of date, or wrong, and they are not legal, financial, tax, or other professional advice. Check anything important before you act on it. Decisions you make based on the service’s output are yours.'
			]
		},
		{
			heading: 'The Market and the Hive Mind',
			paragraphs: [
				'The Market lets you offer editions of a expertise brain to other users for credits. When you list an edition you confirm you have the right to sell its content, and you grant buyers the access described in your listing. We may remove listings that break these terms or the law.',
				'The Hive Mind lets approved specialists offer paid answers from their brains, with a share of each question’s credits going to the specialist. Applications are reviewed by us and may be accepted or declined at our discretion. Earnings are paid in credits.'
			]
		},
		{
			heading: 'Sharing',
			paragraphs: [
				'You control who sees your work. Sharing gives the person you name read-only access to what you share, so share only what you are happy for them to see. You can withdraw a share at any time.'
			]
		},
		{
			heading: 'Acceptable use',
			paragraphs: ['When using the service you must not:'],
			listItems: [
				'upload content that is unlawful, or that infringes someone else’s rights;',
				'attempt to disrupt, overload, probe, or gain unauthorised access to the service;',
				'use the agents to generate unlawful or harmful material;',
				'circumvent credit charges or manipulate credit balances;',
				'resell access to the service except through the Market and the Hive Mind.'
			]
		},
		{
			heading: 'Ending your account',
			paragraphs: [
				'You can stop using the service at any time, and you can ask us to delete your account, which removes your content and any unspent credits — export anything you want to keep first.',
				'We can restrict, suspend, or delete an account that breaks these terms. Where it is reasonable to do so, we will warn you first.'
			]
		},
		{
			heading: 'Our liability',
			paragraphs: [
				'During early access the service is provided as it stands, without warranties beyond those the law implies. Nothing in these terms excludes liability that cannot be excluded under English law, including for death or personal injury caused by negligence, or for fraud.',
				'Beyond that, our total liability to you is limited to the amount you paid us in the 12 months before the event giving rise to the claim, and we are not liable for loss of profit, loss of business, or losses caused by relying on AI-generated output without checking it.'
			]
		},
		{
			heading: 'Changes to these terms',
			paragraphs: [
				'We may update these terms as the service grows. If a change is material we will flag it on the site or by email before it takes effect. Continuing to use the service after a change takes effect means you accept it; if you do not, stop using the service and ask us to delete your account.'
			]
		},
		{
			heading: 'Governing law',
			paragraphs: [
				'These terms are governed by the law of England and Wales, and the courts of England and Wales have jurisdiction over any dispute — although if you are a consumer you keep any protections and venue rights your local law gives you.'
			]
		}
	]
};
